apiVersion: v1
kind: Service
metadata:
  name: cluster-baremetal-webhook-service
  namespace: openshift-machine-api
  labels:
    k8s-app: cluster-baremetal-operator
spec:
  ports:
  - name: https
    port: 443
    targetPort: webhook-server
  selector:
    k8s-app: cluster-baremetal-operator
  sessionAffinity: None
  type: ClusterIP
