apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    service.beta.openshift.io/serving-cert-secret-name: cluster-baremetal-webhook-server-cert
  labels:
    k8s-app: cluster-baremetal-operator
  name: cluster-baremetal-webhook-service
  namespace: openshift-machine-api
spec:
  ports:
  - name: https
    port: 443
    targetPort: webhook-server
  selector:
    k8s-app: cluster-baremetal-operator
  sessionAffinity: None
  type: ClusterIP
